apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-demo-sa
  namespace: sample-workloads
  labels:
    app.kubernetes.io/name: secret-demo
    app.kubernetes.io/component: credential-consumer
    app.kubernetes.io/part-of: production-eks-platform
automountServiceAccountToken: true
